"""Error codes for Animagine MCP."""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Standardized error codes."""

                              
    PROMPT_MISSING_QUALITY_TAG = "PROMPT_MISSING_QUALITY_TAG"
    PROMPT_QUALITY_NOT_LAST = "PROMPT_QUALITY_NOT_LAST"
    PROMPT_TOO_SHORT = "PROMPT_TOO_SHORT"
    PROMPT_MULTIPLE_SERIES = "PROMPT_MULTIPLE_SERIES"
    PROMPT_CHARACTER_NO_SERIES = "PROMPT_CHARACTER_NO_SERIES"
    PROMPT_CONFLICTING_TAGS = "PROMPT_CONFLICTING_TAGS"

                      
    PARAM_RESOLUTION_RISK = "PARAM_RESOLUTION_RISK"

                     
    PIPELINE_INIT_FAILED = "PIPELINE_INIT_FAILED"
    CUDA_NOT_AVAILABLE = "CUDA_NOT_AVAILABLE"
    OUT_OF_MEMORY = "OUT_OF_MEMORY"

                            
    CHECKPOINT_NOT_FOUND = "CHECKPOINT_NOT_FOUND"
    CHECKPOINT_LOAD_FAILED = "CHECKPOINT_LOAD_FAILED"
    LORA_NOT_FOUND = "LORA_NOT_FOUND"
    LORA_LOAD_FAILED = "LORA_LOAD_FAILED"
    LORA_INCOMPATIBLE = "LORA_INCOMPATIBLE"
    MODEL_NOT_LOADED = "MODEL_NOT_LOADED"

                    
    SOURCE_IMAGE_NOT_FOUND = "SOURCE_IMAGE_NOT_FOUND"
    SOURCE_IMAGE_INVALID = "SOURCE_IMAGE_INVALID"

                
    DEFAULT_NEGATIVE_APPLIED = "DEFAULT_NEGATIVE_APPLIED"
